os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  # Needed for Locale::Object
  - cpanm --quiet --installdeps --notest DBD::SQLite
  - cpanm --installdeps --notest Locale::Object
  - cpanm --installdeps --notest .
