os:
  - linux
  - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  # Needed for Locale::Object
  - cpanm --installdeps --notest DBD::SQLite Locale::Object::Country || cat /home/travis/.cpanm/work/*/build.log
  - cpanm --installdeps --notest . || cat /home/travis/.cpanm/work/*/build.log
